import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
size = 14.0

normal.family = "JetBrainsMono Nerd Font Mono"
